version: 2.1
orbs:
  node: circleci/node@3.0.0

dependencies:
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn

install:
  override:
    - yarn install

test:
  override:
    - yarn test

workflows:
  node-tests:
    jobs:
      - node/test
